introduction: |-
    This is the Node.js Server SDK for [Google Cloud Firestore](https://firebase.google.com/docs/firestore/). Google Cloud Firestore is a NoSQL document database built for automatic scaling, high performance, and ease of application development.

    This Cloud Firestore Server SDK uses Google’s Cloud Identity and Access Management for authentication and should only be used in trusted environments. Your Cloud Identity credentials allow you bypass all access restrictions and provide read and write access to all data in your Cloud Firestore project.

    The Cloud Firestore Server SDKs are designed to manage the full set of data in your Cloud Firestore project and work best with reliable network connectivity. Data operations performed via these SDKs directly access the Cloud Firestore backend and all document reads and writes are optimized for high throughput.

    Applications that use Google&#x27;s Server SDKs should not be used in end-user environments, such as on phones or on publicly hosted websites. If you are developing a Web or Node.js application that accesses Cloud Firestore on behalf of end users, use the firebase Client SDK.

    **Note:** This Cloud Firestore Server SDK does not support Firestore databases created in [Datastore mode](https://cloud.google.com/datastore/docs/firestore-or-datastore#in_datastore_mode). To access these databases, use the [Datastore SDK](https://www.npmjs.com/package/@google-cloud/datastore).

body: |-
    
    ### Using the client library with Pipelines
    
    ```javascript
    
    const {Firestore} = require('@google-cloud/firestore');
    
    // Require/import Pipelines from '@google-cloud/firestore/pipelines'
    const {field} = require('@google-cloud/firestore/pipelines');
    
    // Create a new client
    const firestore = new Firestore({
      projectId: 'firestore-sdk-nightly',
      databaseId: 'enterprise'
    });
    
    async function pipelinesQuickstart() {
      // Obtain a collection reference.
      const collection = firestore.collection('books');
    
      // Enter new documents into the document.
      await collection.add({
        "title": "Whispers of the Cobalt Sea",
        "price": 12.99,
        "author": "Elara Vance",
        "yearPublished": 2023
      });
      await collection.add({
        "title": "The Antigravity Cat's Guide to Napping",
        "price": 24.50,
        "author": "Mittens the IV",
        "yearPublished": 2026
      });
      console.log('Entered new documents into the collection.');
    
      // Define a Pipeline query that selects books published this century,
      // orders them by price, and computes a discounted price (20% off).
      const pipeline = firestore.pipeline().collection('books')
          .where(field('yearPublished').greaterThanOrEqual(2000))
          .sort(field('price').ascending())
          .select('title', 'author', field('price').multiply(0.8).as('discountedPrice'));
    
      // Execute the pipeline
      const pipelineSnapshot = await pipeline.execute();
      console.log('Executed the Pipeline.');
    
      console.log('Results:');
      pipelineSnapshot.results.forEach(pipelineResult=> {
        console.log(pipelineResult.data());
      });
    }
    pipelinesQuickstart();
    
    ```
