version: 2
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node6:
          filters: *all_commits
      - node8:
          filters: *all_commits
      - node9:
          filters: *all_commits
      - node10:
          filters: *all_commits
      - docs:
          requires:
            - node6
            - node8
            - node9
            - node10
          filters: *all_commits
      - system_tests:
          requires:
            - docs
          filters:
            branches:
              only: master
            tags: &releases
              only: '/^v[\d.]+$/'
      - publish_npm:
          requires:
            - system_tests
          filters:
            branches:
              ignore: /.*/
            tags: *releases
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs
jobs:
  node6:
    docker:
      - image: 'node:6'
        user: node
    steps: *unit_tests_steps
  node8:
    docker:
      - image: 'node:8'
        user: node
    steps: *unit_tests_steps
  node9:
    docker:
      - image: 'node:9'
        user: node
    steps: *unit_tests_steps
  node10:
    docker:
      - image: 'node:10'
        user: node
    steps: *unit_tests_steps
  docs:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run: *remove_package_lock
      - run: *npm_install_and_link
      - run:
          name: Build documentation.
          command: npm run docs
  system_tests:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run: *remove_package_lock
      - run:
          name: Decrypt credentials.
          command: |
            openssl aes-256-cbc -d -in .circleci/key.json.enc \
                -out .circleci/key.json \
                -k "${SYSTEM_TESTS_ENCRYPTION_KEY}"
      - run: *npm_install_and_link
      - run:
          name: Run system tests.
          command: npm run system-test
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: .circleci/key.json
            GCLOUD_PROJECT: node-gcloud-ci
            GCLOUD_TESTS_KEY: .circleci/key.json
            GCLOUD_TESTS_PROJECT_ID: node-gcloud-ci
      - run:
          name: Remove unencrypted key.
          command: rm .circleci/key.json
          when: always
  publish_npm:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run:
          name: Set NPM authentication.
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Publish the module to npm.
          command: npm publish
