// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export {
  Pipeline,
  PipelineResult,
  PipelineSnapshot,
  PipelineSource,
} from './pipelines';

export {
  and,
  arrayContains,
  arrayContainsAny,
  arrayReverse,
  average,
  equal,
  ceil,
  exp,
  floor,
  greaterThan,
  like,
  lessThan,
  notEqual,
  ascending,
  not,
  or,
  regexContains,
  regexMatch,
  startsWith,
  stringConcat,
  subtract,
  cosineDistance,
  countDistinct,
  dotProduct,
  euclideanDistance,
  mapGet,
  lessThanOrEqual,
  equalAny,
  map,
  array,
  field,
  xor,
  AggregateFunction,
  rand,
  arrayGet,
  add,
  BooleanExpression,
  Expression,
  FunctionExpression,
  minimum,
  count,
  countIf,
  arrayLength,
  stringContains,
  charLength,
  divide,
  mod,
  reverse,
  trim,
  toUpper,
  toLower,
  vectorLength,
  isNotNan,
  exists,
  isNotNull,
  isAbsent,
  ifError,
  isError,
  isNan,
  substring,
  documentId,
  isNull,
  arrayContainsAll,
  constant,
  Field,
  Constant,
  sum,
  maximum,
  descending,
  greaterThanOrEqual,
  multiply,
  conditional,
  Ordering,
  AliasedAggregate,
  endsWith,
  AliasedExpression,
  mapMerge,
  mapRemove,
  byteLength,
  logicalMaximum,
  logicalMinimum,
  notEqualAny,
  countAll,
  timestampAdd,
  timestampSubtract,
  timestampToUnixMicros,
  timestampToUnixSeconds,
  unixMicrosToTimestamp,
  timestampToUnixMillis,
  unixSecondsToTimestamp,
  unixMillisToTimestamp,
  pow,
  collectionId,
  length,
  ln,
  log,
  round,
  sqrt,
  stringReverse,
  // TODO(new-expression): Add new expression exports above this line
} from './expression';
