// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export {
  Pipeline,
  PipelineResult,
  PipelineSnapshot,
  PipelineSource,
} from './pipelines';

export {
  and,
  arrayContains,
  arrayContainsAny,
  avg,
  eq,
  gt,
  like,
  lt,
  neq,
  ascending,
  not,
  or,
  regexContains,
  regexMatch,
  startsWith,
  strConcat,
  subtract,
  cosineDistance,
  dotProduct,
  euclideanDistance,
  mapGet,
  lte,
  eqAny,
  map,
  array,
  bitNot,
  field,
  xor,
  AggregateFunction,
  rand,
  arrayOffset,
  add,
  BooleanExpr,
  Expr,
  FunctionExpr,
  minimum,
  count,
  countIf,
  arrayLength,
  strContains,
  charLength,
  divide,
  mod,
  reverse,
  trim,
  toUpper,
  toLower,
  vectorLength,
  isNotNan,
  exists,
  isNotNull,
  isAbsent,
  ifError,
  isError,
  isNan,
  arrayConcat,
  substr,
  documentId,
  isNull,
  arrayContainsAll,
  constant,
  constantVector,
  Field,
  Constant,
  sum,
  maximum,
  descending,
  gte,
  bitOr,
  bitXor,
  bitLeftShift,
  bitRightShift,
  bitAnd,
  multiply,
  cond,
  Ordering,
  AggregateWithAlias,
  endsWith,
  ExprWithAlias,
  mapMerge,
  mapRemove,
  byteLength,
  logicalMaximum,
  logicalMinimum,
  notEqAny,
  countAll,
  replaceAll,
  replaceFirst,
  timestampAdd,
  timestampSub,
  timestampToUnixMicros,
  timestampToUnixSeconds,
  unixMicrosToTimestamp,
  timestampToUnixMillis,
  unixSecondsToTimestamp,
  unixMillisToTimestamp,
} from './expression';

export {FindNearestOptions} from './stage';
